### ISSUE TITLE
error handling should be added when priority level is larger than the number of nodes - 1 in TSP-PRI

### ISSUE THREAD

**Issue by aki916** [Thinklab-SJTU/LinSATNet#5]
https://github.com/Thinklab-SJTU/LinSATNet/blob/bf4a44a6b0f5aa241dfb1a623426c573378e9aa2/TSP_exp/utils/project.py#L26-L48

The following scripts should be added in L27 
```
    if priority_level > node_num - 1:
        priority_level = node_num - 1
        print("FIXME : appropriate message")
```

**Comment by YunhaoZhang-Mars** [comment]
Thanks for providing this corner case and the following is a detailed analysis:

In this problem, the second node should be visited within the first $priority\\_level$ steps. As we are dealing with TSP with starting and ending nodes, the number of steps to take is $node\\_num - 1$. The last step must be from an intermedium node to the ending node, so the remaining number of steps is $node\\_num - 2$. Therefore, when $priority\\_level \ge node\\_num - 2$, the 
 priory constraint is redundant and the problem degenerates to TSP-SE.  So a more efficient implement should be: if $priority\\_level \ge node\\_num - 2$, not adding the last constraint (the shape of $A, b$ matrices need to change); else,  adding it.

**Comment by rogerwwww** [comment]
I am closing this issue --- feel free to reopen it if the issue still exists!
